version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -LO https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip
      - unzip -o terraform_1.6.6_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
      - ls -la

  pre_build:
    commands:
      - cd terraform_infra
      - terraform init -backend-config="bucket=selmicapstones3" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1" -backend-config="dynamodb_table=terraform-lock-table"
      - echo "Importing existing AWS resources into Terraform..."
      - terraform import aws_iam_role.rds_enhanced_monitoring task-db-postgres-rds-enhanced-monitoring-role || true
      - terraform import aws_iam_role.eks_cluster three-tier-eks-cluster-eks-cluster-role || true
      - terraform import aws_iam_role.eks_node_group three-tier-eks-cluster-eks-node-group-role || true
      - terraform import aws_db_subnet_group.this task-db-postgres-subnet-group || true
      - terraform import 'module.eks.aws_cloudwatch_log_group.this[0]' /aws/eks/three-tier-eks-cluster/cluster
      - terraform import 'module.eks.module.kms.aws_kms_alias.this["cluster"]' alias/eks/three-tier-eks-cluster


  build:
    commands:
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan
