apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: taskns
  labels:
    app: taskns
data:
  # Database configuration (AWS RDS)
  DB_HOST: "task-db-postgres.cd28oacw4o6t.us-east-2.rds.amazonaws.com"  # Replace with your RDS endpoint
  DB_PORT: "5432"
  DB_NAME: "taskflow_db"
  DB_USER: "postgres"
  
  # Backend configuration
  NODE_ENV: "production"
  PORT: "5000"
  
  # Frontend configuration
  REACT_APP_API_URL: "/api"
