apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: taskns
  labels:
    app: taskns
type: Opaque
data:
  # Base64 encoded values
  # password -> cGFzc3dvcmQ=
  # postgres -> cG9zdGdyZXM=
  POSTGRES_PASSWORD: dGFzazA5ODc=
  POSTGRES_USER: cG9zdGdyZXM=
  DB_PASSWORD: dGFzazA5ODc=
